repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort

-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        name: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.780
    hooks:
    -   id: mypy


default_language_version:
    python: python3.8
